import { defineConfig } from "vite";
import react from "@vitejs/plugin-react-swc";
import path from "path";
import fs from "fs";
import os from "os";
import { componentTagger } from "lovable-tagger";

export default defineConfig(({ mode }) => {
  const isDev = mode === "development";

  // Port linh hoạt:
  // - Mặc định 5173 (Vite default, không trùng với các service khác)
  // - Có thể override bằng env: VITE_PORT hoặc PORT
  // - Hoặc chạy: npm run dev -- --port 5173 (Vite tự nhận)
  const port = Number(process.env.VITE_PORT || process.env.PORT || 5173);

  // Auto-detect HTTPS certificates (generated by setup-https.ps1)
  const certPath = path.resolve(__dirname, "dev-cert.pem");
  const keyPath = path.resolve(__dirname, "dev-cert-key.pem");
  const hasHttpsCert = fs.existsSync(certPath) && fs.existsSync(keyPath);

  // Detect API Gateway URL
  // Ưu tiên: env var > IP máy tính (để điện thoại truy cập được) > localhost fallback
  let apiGatewayUrl = process.env.VITE_API_GATEWAY;
  
  if (!apiGatewayUrl) {
    // Tự động detect IP của máy tính để điện thoại có thể kết nối
    const networkInterfaces = os.networkInterfaces();
    let localIP = 'localhost';
    
    // Tìm IP 192.168.x.x
    for (const interfaceName in networkInterfaces) {
      const iface = networkInterfaces[interfaceName];
      if (iface) {
        for (const addr of iface) {
          if (addr.family === 'IPv4' && !addr.internal && addr.address.startsWith('192.168.')) {
            localIP = addr.address;
            break;
          }
        }
      }
    }
    
    apiGatewayUrl = `http://${localIP}:8888`;
  }
  
  console.log(`[Vite] API Gateway URL: ${apiGatewayUrl}`);

  return {
    server: {
      // Để điện thoại truy cập bằng IPv4 LAN cho chắc
      host: true, // tương đương 0.0.0.0
      port,
      strictPort: true, // KHÔNG tự nhảy port (khuyến nghị để khỏi lệch CORS/flow)

      // Proxy /api/* -> API Gateway
      proxy: {
        '/api': {
          target: apiGatewayUrl,
          changeOrigin: true,
          secure: false,
          // rewrite: (path) => path.replace(/^\/api/, ''), // Giữ nguyên /api prefix
        },
      },

      // // HTTPS dùng mkcert (tự động bật nếu có cert)
      // https: isDev && hasHttpsCert
      //   ? {
      //       key: fs.readFileSync("D:/DACNTT/A-microservices-based-e-learning-platform/client/dev-cert-key.pem"),
      //       cert: fs.readFileSync("D:/DACNTT/A-microservices-based-e-learning-platform/client/dev-cert.pem"),
      //     }
      //   : undefined,
    },

    plugins: [react()].filter(Boolean),

    resolve: {
      alias: {
        "@": path.resolve(__dirname, "./src"),
      },
    },

    build: {
      outDir: "dist",
      emptyOutDir: true,
      minify: "esbuild", // Dùng esbuild thay vì terser (nhanh hơn và built-in)
      target: "esnext",
    },
  };
});
